name: run the tests

on: [pull_request]
env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/bioptim

          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envsbioptim

          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\bioptim

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: bioptim
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n bioptim -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install extra packages
        run: mamba install pytest-cov black pytest pytest-cov codecov -cconda-forge

      - name: Check if blacked
        shell: bash
        run: black . -l120 --exclude "external/*" --check
        if: matrix.label == 'linux-64'

      - name: Install ACADOS on Linux
        run: |
          cd external
          ./acados_install_linux.sh
          cd ..
        if: matrix.label == 'linux-64'

      - name: Install ACADOS on Mac
        run: |
          cd external
          ./acados_install_mac.sh
          cd ..
        if: matrix.label == 'osx-64'

      - name: Run tests
        shell: bash -l {0}
        run: pytest -v --color=yes --cov-report term-missing --cov=bioptim tests

      - name: Install bioptim
        shell: bash -l {0}
        run: python setup.py install

      - name: Upload coverage to Codecov
        shell: bash -l {0}
        run: codecov
        if: matrix.label == 'linux-64'
