name: run the tests

on: [pull_request]
env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  default-shell:
    name: Default shell
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: bioptim
          environment-file: environment.yml
          use-mamba: true
        
      - name: Print info
        run: | 
          mamba config --show
          mamba info
          mamba list
      
      - name: Install extra dependencies
        run: mamba install pytest-cov black pytest pytest-cov codecov -cconda-forge
        
      - name: Test installed version of bioptim
        shell: bash
        run: | 
          python setup.py install
          cd
          python -c "import biorbd"
          
