name: run the tests

on: [pull_request]
env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  default-shell:
    name: Default shell
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: bioptim
          environment-file: environment.yml
          use-mamba: true
      - run: mamba info
      - run: mamba list
      - run: mamba config --show
      - run: mamba install biorbd -cconda-forge
      - run: python -c "import biorbd"
